# Generated by Django 3.2 on 2025-04-01 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_moderatorsetuped_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModeratorSetuped',
        ),
    ]
