# Generated by Django 3.2 on 2025-04-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_delete_moderatorsetuped"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customabstractuser",
            name="avatar",
        ),
        migrations.RemoveField(
            model_name="customabstractuser",
            name="given_name",
        ),
        migrations.RemoveField(
            model_name="customabstractuser",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="customabstractuser",
            name="rating",
        ),
        migrations.AlterField(
            model_name="customabstractuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="customabstractuser",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="customabstractuser",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
    ]
