# Generated by Django 3.2 on 2025-04-21 08:54

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20250401_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='customabstractuser',
            name='user_type',
            field=models.TextField(choices=[('BUYER', 'Покупатель'), ('SELLER', 'Продавец'), ('ADMIN', 'Администратор'), ('DELIVERY', 'Доставщик'), ('SUPPORT', 'Поддержка'), ('MODERATOR', 'Модератор')], default=users.models.CustomAbstractUser.UserType['BUYER'], verbose_name='Тип пользователя'),
        ),
    ]
