# Generated by Django 3.2 on 2025-04-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_customabstractuser_user_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customabstractuser",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="customabstractuser",
            name="password",
        ),
        migrations.AddField(
            model_name="customabstractuser",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
