# Generated by Django 3.2 on 2025-04-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_auto_20250421_1501"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customabstractuser",
            name="user_type",
            field=models.TextField(
                choices=[
                    ("BUYER", "Покупатель"),
                    ("SELLER", "Продавец"),
                    ("ADMIN", "Администратор"),
                    ("DELIVERY", "Доставщик"),
                    ("SUPPORT", "Поддержка"),
                    ("MODERATOR", "Модератор"),
                ],
                default="Покупатель",
                verbose_name="Тип пользователя",
            ),
        ),
    ]
