# Generated by Django 3.2 on 2025-04-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_alter_customabstractuser_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="customabstractuser",
            name="sex",
            field=models.TextField(
                choices=[("MALE", "Мужчина"), ("FEMALE", "Женщина")],
                null=True,
                verbose_name="Пол пользователя",
            ),
        ),
    ]
