# Generated by Django 3.2 on 2025-04-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_customabstractuser_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customabstractuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customabstractuser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='customabstractuser',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя'),
        ),
    ]
