# Generated by Django 3.2 on 2025-04-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_auto_20250429_1213"),
    ]

    operations = [
        migrations.AddField(
            model_name="customabstractuser",
            name="otp_expires",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время жизни otp"
            ),
        ),
    ]
