# Generated by Django 3.2 on 2025-05-05 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_customabstractuser_otp_expires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customabstractuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customabstractuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customabstractuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customabstractuser',
            name='is_superuser',
        ),
    ]
