# Generated by Django 3.2 on 2025-05-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_auto_20250505_0900"),
    ]

    operations = [
        migrations.AddField(
            model_name="customabstractuser",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
