# Generated by Django 3.2 on 2025-05-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_customabstractuser_is_active'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='customabstractuser',
        #     name='name',
        # ),
        # migrations.AddField(
        #     model_name='customabstractuser',
        #     name='first_name',
        #     field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        # ),
        # migrations.AddField(
        #     model_name='customabstractuser',
        #     name='last_name',
        #     field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        # ),
    ]
