# Generated by Django 3.2 on 2025-05-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20250510_0531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customabstractuser',
            name='name',
        ),
        migrations.AddField(
            model_name='customabstractuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='customabstractuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
