# Generated by Django 3.2 on 2025-05-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20250510_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='customabstractuser',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatars', verbose_name='Аватар'),
        ),
    ]
