# Generated by Django 3.2 on 2025-03-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkout",
            name="payment_total",
            field=models.FloatField(verbose_name="Сумма"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.FloatField(verbose_name="Сумма платежа"),
        ),
    ]
