# Generated by Django 3.2 on 2025-03-28 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20250327_1229"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="basket",
            options={"verbose_name": "Корзина", "verbose_name_plural": "Корзины"},
        ),
        migrations.AlterModelOptions(
            name="basketitem",
            options={
                "verbose_name": "Товар в корзине",
                "verbose_name_plural": "Товары в корзине",
            },
        ),
        migrations.AlterModelOptions(
            name="checkout",
            options={"verbose_name": "Счет", "verbose_name_plural": "Счета"},
        ),
        migrations.AlterModelOptions(
            name="deliverymethod",
            options={
                "verbose_name": "Способ доставки",
                "verbose_name_plural": "Способы доставки",
            },
        ),
        migrations.AlterModelOptions(
            name="goodcategory",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="gooditem",
            options={"verbose_name": "Товар", "verbose_name_plural": "Товары"},
        ),
        migrations.AlterModelOptions(
            name="paymentmethod",
            options={
                "verbose_name": "Способ оплаты",
                "verbose_name_plural": "Способы оплаты",
            },
        ),
        migrations.AlterModelOptions(
            name="recipent",
            options={"verbose_name": "Получатель", "verbose_name_plural": "Получатели"},
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={"verbose_name": "Транзакция", "verbose_name_plural": "Транзакции"},
        ),
    ]
