# Generated by Django 3.2 on 2025-03-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_auto_20250328_0927"),
    ]

    operations = [
        migrations.AddField(
            model_name="basket",
            name="visible",
            field=models.BooleanField(default=True, verbose_name="Видимая"),
        ),
    ]
