# Generated by Django 3.2 on 2025-04-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_auto_20250421_1633"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.TextField(
                choices=[
                    ("PAYED", "Оплачен"),
                    ("PROCESSING", "В обработке"),
                    ("ON_THE_WAY", "В пути"),
                    ("DELIVERED", "Доставлен"),
                    ("RECEIVED", "Получен"),
                    ("REFUND", "Возврат"),
                    ("DECLINED", "Отклонен"),
                ],
                default="В обработке",
                verbose_name="Статус",
            ),
        ),
    ]
