# Generated by Django 3.2 on 2025-04-22 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.order",
                verbose_name="Ответ от платежной системы",
            ),
        ),
    ]
