# Generated by Django 3.2 on 2025-04-25 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_auto_20250422_1451"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="itemcharacteristic",
            unique_together={("item", "characteristic")},
        ),
    ]
