# Generated by Django 3.2 on 2025-04-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20250425_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_cvc_code',
            field=models.IntegerField(verbose_name='CVC код'),
        ),
    ]
