# Generated by Django 3.2 on 2025-04-29 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_paymentmethod_card_cvc_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='card_cvc_code',
            new_name='card_cvv_code',
        ),
    ]
