# Generated by Django 3.2 on 2025-04-29 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_rename_card_cvc_code_paymentmethod_card_cvv_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipent",
            name="phone",
        ),
        migrations.AddField(
            model_name="recipent",
            name="phone_number",
            field=models.CharField(
                default=79089190401,
                max_length=12,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Номер телефона должен быть введен в формате +7XXXXXXXXXX.",
                        regex="^\\+7\\d{10}$",
                    )
                ],
                verbose_name="Номер телефона",
            ),
            preserve_default=False,
        ),
    ]
