# Generated by Django 3.2 on 2025-05-10 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_paymentmethod_bank_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="order",
        ),
    ]
