# Generated by Django 3.2 on 2025-05-12 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20250512_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='bank_name',
        ),
    ]
