# Generated by Django 3.2 on 2025-05-14 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_auto_20250512_1238"),
    ]

    operations = [
        migrations.AddField(
            model_name="basket",
            name="parent",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.basket"
            ),
        ),
    ]
