# Generated by Django 3.2 on 2025-05-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_auto_20250515_1227"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refund",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="создан"),
        ),
    ]
