# Generated by Django 3.2 on 2025-05-19 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_auto_20250519_1519"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentmedia",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="api.comment",
                verbose_name="отзыв",
            ),
        ),
    ]
