# Generated by Django 3.2 on 2025-05-21 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodcategory',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daughter', to='api.goodcategory', verbose_name='Родительская категория'),
        ),
    ]
