# Generated by Django 3.2 on 2025-05-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_goodcategory_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='checkout_id',
            field=models.CharField(default='', max_length=40, verbose_name='Айди чекаута YoMoney'),
            preserve_default=False,
        ),
    ]
