# Generated by Django 3.2 on 2025-05-24 13:56

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_moneypayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneypayout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moneypayout',
            name='good_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.gooditem', verbose_name='Товар'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moneypayout',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.expressions.Case, to='api.order', verbose_name='Заказ'),
            preserve_default=False,
        ),
    ]
