# Generated by Django 3.2 on 2025-05-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20250524_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneypayout',
            name='state',
            field=models.TextField(choices=[('REFUND', 'Возврат'), ('PAYOUT', 'Выплата'), ('FREEZED', 'Заморожен')], default='FREEZED', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.TextField(choices=[('PAYED', 'Оплачен'), ('PROCESSING', 'В обработке'), ('ON_THE_WAY', 'В пути'), ('DELIVERED', 'Доставлен'), ('RECEIVED', 'Получен'), ('REFUND', 'Возврат'), ('DECLINED', 'Отклонен')], default='PROCESSING', verbose_name='Статус'),
        ),
    ]
