# Generated by Django 3.2 on 2025-05-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_auto_20250525_1334"),
    ]

    operations = [
        migrations.AddField(
            model_name="gooditem",
            name="warehouse_count",
            field=models.IntegerField(default=0, verbose_name="Количество на складе"),
        ),
    ]
