# Generated by Django 3.2 on 2025-05-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.TextField(choices=[('REFUND_POLICY', 'Политика возвратов'), ('OTHER', 'Другие'), ('OFFER', 'Оферта'), ('PLATFORM_RULES', 'Правила платформы'), ('USER_REGLAMENT', 'Пользовательское соглашение'), ('PLATFORM_POLICY', 'Политика платформы')], default='OTHER', verbose_name='Тип'),
        ),
    ]
